### PR TITLE
Was able to get the Acer Lenses to work with the project with viewing the scene and interacting with the UI.

### PR DESCRIPTION
**Pull request by nrebei2**
Note: The Windows MR Headset require a later version of Unity, specifically 2017.2.1p2, as well as needing to be built on the Windows Universal Platform in the build settings.

### CODE REVIEW

**Comment by sujayshah** [comment]
How did porting the project to a later version of Unity go?

**Comment by nrebei2** [comment]
It went pretty well, but I'm getting an error when I try to build the asset bundles:

ArgumentNullException: Argument cannot be null.
Parameter name: path2
System.IO.Path.Combine (System.String path1, System.String path2) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/Path.cs:115)
AssetBundles.BuildScript.BuildAssetBundles () (at Assets/AssetBundleManager/Editor/BuildScript.cs:19)
AssetBundles.AssetBundlesMenuItems.BuildAssetBundles () (at Assets/AssetBundleManager/Editor/AssetbundlesMenuItems.cs:27)

**Comment by nrebei2** [comment]
It runs in the editor just fine, but when I build the app the molecules don't load ¯ \_(ツ)_/¯

**Comment by EmiCB** [comment]
I looked through the Unity 2017.2 changelog (https://unity3d.com/unity/whats-new/unity-2017.2.0 ), but I don't know a whole lot about asset bundles. I found a couple changes that might relate to the problem:
- “Package Manager: Moved the location of the project packages manifest from /UnityPackageManager/Project to /UnityPackageManager.”
- “Asset Pipeline: AddedAssetBundle.UnloadAllAssetBundles() and AssetBundle.GetAllLoadedAssetBundles(). (904927)”
- “Kernel: Added new AssetBundle APIs LoadFromStream and LoadFromStreamAsync. The APIs let the user load AssetBundle data from a managed Stream instead of Unity native methods.”

**Comment by sujayshah** [comment]
Those are some good points. We're planning on overhauling the way we handle assetbundles anyway. For now, I'll leave the pull request open while we fix assetbundles. Then, we can test it again.

We'll discuss it in detail on Thursday

**Comment by nrebei2** [comment]
Whoops, I got it to work, but I don't think it will be too hard to get it to work again after you overhaul the assetbundles.

**Comment by sujayshah** [comment]
Sounds good, we'll have a demo tomorrow

**Pull request closed without merging**
